version: '3.5'

services:
  photoviewer:
    container_name: photoviewer
    build:
      context: ./ 
      dockerfile: Dockerfile
    volumes:
      - albums:/usr/src/app/PhotoFloat/web/albums
      - cache:/usr/src/app/PhotoFloat/web/cache
    ports:
      - '2020:2020'
    networks:
      - nest
    restart: on-failure

# TODO: have only albums and make 
# resized and faces folders as its children    
volumes:
  albums:
  resized_albums:
  faces:
  cache:
  pgdata:

networks:
  nest:




