version: '3.5'

services:

  imguploadservice:
    container_name: imguploadservice
    build:
      context: ../../src/imguploadservice
      dockerfile: Dockerfile
    volumes:
      - albums:/usr/src/app/uploads
    ports:
      - '8000:8000'
    networks:
      - nest

# TODO: have only albums and make 
# resized and faces folders as its children    
volumes:
  albums:
  resized_albums:
  faces:
  cache:
  pgdata:

networks:
  nest:




