baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "kuruvitheme"
relativeURLs = true

[menu]
  [[menu.main]]
    identifier = "photos"
    name = "Photos"
    url = "/photos/"
    weight = 100

[[menu.main]]
    name = "Try PhotoSwipe"
    url = "/galleries/"
    weight = 110
