baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "kuruvitheme"
relativeURLs = true

[[menu.main]]
    name = "Gallery"
    url = "/galleries/"
    weight = 100
