
version: '3.5'

services:
  postgres-db:
    container_name: postgres-db
    build:
      context: ./postgres-db
      dockerfile: Dockerfile

  postgres-api:
    container_name: postgres-api
    build:
      context: ./postgres-api
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    restart: on-failure

  pgadmin4:
    container_name: pgadmin4
    image: "thajeztah/pgadmin4"
    ports:
      - "5050:5050"
