---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
  # namespace: kuruvi
spec:
  type: LoadBalancer
  ports:
  - port: 8079
    targetPort: 8079
  selector:
    name: front-end
