apiVersion: v1
kind: PersistentVolume
metadata:
  name: album-uploads
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"