---
apiVersion: v1
kind: Service
metadata:
  name: servicex
  labels:
    name: servicex
  # namespace: kuruvi
spec:
  type: LoadBalancer
  ports:
  - port: 8002
    targetPort: 8002
  selector:
    name: servicex
