---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: servicex
  labels:
    name: servicex
  # namespace: kuruvi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: servicex
    spec:
      containers:
      - name: servicex
        image: yokesht/servicex:0.0.1
        ports:
        - containerPort: 8002
        securityContext:
          capabilities:
            drop:
              - all
            add:
              # - CHOWN
              # - SETGID
              # - SETUID
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux