---
apiVersion: v1
kind: Service
metadata:
  name: photo-upload-server
  labels:
    name: photo-upload-server
  # namespace: kuruvi
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    name: photo-upload-server
