---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: photo-upload-server
  labels:
    name: photo-upload-server
  # namespace: kuruvi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: photo-upload-server
    spec:
      containers:
      - name: photo-upload-server
        image: yokesht/photo-upload-server:0.0.2
        ports:
        - containerPort: 8000
        securityContext:
          capabilities:
            drop:
              - all
            add:
              # - CHOWN
              # - SETGID
              # - SETUID
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /srv/album-uploads
          name: album-uploads
      volumes:
        - name: album-uploads
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux