version: '3.5'

services:
  frontend:
    container_name: ${FRONTEND_SERVICE}
    build:
      context: ./ 
      args:
        - PORT:${FRONTEND_PORT}
      dockerfile: Dockerfile
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    restart: on-failure
