version: '3.5'

services:
  exif-core:
    container_name: ${EXIF_CORE_SERVICE}
    build:
      context: ./exif-core
      dockerfile: Dockerfile
      args:
        EXIF_CORE_PORT: ${EXIF_CORE_PORT}
    restart: on-failure

  exif-api:
    container_name: ${EXIF_API_SERVICE}
    build:
      context: ./exif-api
      dockerfile: Dockerfile
      args:
        EXIF_API_PORT: ${EXIF_API_PORT}
    restart: on-failure

  exif-queue:
    container_name: ${EXIF_QUEUE_SERVICE}
    build:
      context: ./exif-queue
      dockerfile: Dockerfile
    restart: on-failure