version: '3.5'

services:
  photo-upload-server:
    container_name: ${PHOTO_UPLOAD_SERVER_SERVICE}
    build:
      context: ./photo-upload-server
      dockerfile: Dockerfile
      args:
        PHOTO_UPLOAD_SERVER_PORT: ${PHOTO_UPLOAD_SERVER_PORT}
    volumes:
      - album-uploads:/srv/album-uploads
    ports:
      - ${PHOTO_UPLOAD_SERVER_PORT}:${PHOTO_UPLOAD_SERVER_PORT}
    restart: on-failure

  caddy-server:
    container_name: ${CADDY_SERVER_SERVICE}
    build:
      context: ./caddy-server
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - album-uploads:/srv/album-uploads
    ports:
      - ${CADDY_SERVER_PORT}:${CADDY_SERVER_PORT}

  static-generator:
    container_name: ${STATIC_GENERATOR_SERVICE}
    build:
      context: ./static-generator
      dockerfile: Dockerfile
      args:
        STATIC_GENETATOR_PORT: ${STATIC_GENERATOR_PORT}
    restart: on-failure
    ports:
      - ${STATIC_GENERATOR_PORT}:${STATIC_GENERATOR_PORT}
    volumes:
      - album-uploads:/srv/album-uploads
      # - album-faces:/srv/album-faces
      # - album-resized:/srv/album-resized
      - album-static-gen:/srv/album-static-gen

volumes:
  album-faces:
  album-resized:
  album-static-gen:
  album-uploads:
  # postgres-data: