version: '3.5'

services:
  face-api:
    container_name: ${FACE_API_SERVICE}
    build:
      context: ./face-api
      dockerfile: Dockerfile
      args:
        FACE_API_PORT: ${FACE_API_PORT}
    restart: on-failure

  face-queue:
    container_name: ${FACE_QUEUE_SERVICE}
    build:
      context: ./face-queue
      dockerfile: Dockerfile
    restart: on-failure
  
  face-detect:
    container_name: ${FACE_DETECT_SERVICE}
    build:
      context: ./face-detect
      dockerfile: Dockerfile
      args:
        FACE_DETECT_PORT: ${FACE_DETECT_PORT}
    restart: on-failure

  face-describe:
    container_name: ${FACE_DESCRIBE_SERVICE}
    build:
      context: ./face-describe
      dockerfile: Dockerfile
      args:
        FACE_DETECT_PORT: ${FACE_DESCRIBE_PORT}
    restart: on-failure

  face-crop:
    container_name: ${FACE_CROP_SERVICE}
    build:
      context: ./face-crop
      dockerfile: Dockerfile
      args:
        FACE_CROP_PORT: ${FACE_CROP_PORT}
    volumes:
      - album-faces:/srv/faces
    restart: on-failure

  face-crop-server:
    container_name: ${FACE_CROP_SERVER_SERVICE}
    build:
      context: ./face-crop-server
      dockerfile: Dockerfile
    restart: on-failure

volumes:
  album-faces: