version: '3.5'

services:
  frontend:
    container_name: ${FRONTEND_SERVICE}
    build:
      context: ../../src/frontend 
      dockerfile: Dockerfile
    environment:
     - FRONTEND_PORT=${FRONTEND_PORT}
    ports:
     - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
     - album-static-gen:/srv
    restart: on-failure

  photo-upload-server:
    container_name: ${PHOTO_UPLOAD_SERVER_SERVICE}
    build:
      context: ../../src/storage/photo-upload-server
      dockerfile: Dockerfile
      args:
        PHOTO_UPLOAD_SERVER_PORT: ${PHOTO_UPLOAD_SERVER_PORT}
    volumes:
      - album-uploads:/srv/album-uploads
    ports:
      - ${PHOTO_UPLOAD_SERVER_PORT}:${PHOTO_UPLOAD_SERVER_PORT}
    restart: on-failure

  caddy-server:
    container_name: ${CADDY_SERVER_SERVICE}
    build:
      context: ../../src/storage/caddy-server
      dockerfile: Dockerfile
    volumes:
      - album-uploads:/srv/album-uploads
    ports:
      - ${CADDY_SERVER_PORT}:${CADDY_SERVER_PORT}
    restart: on-failure

  static-generator:
    container_name: ${STATIC_GENERATOR_SERVICE}
    build:
      context: ../../src/storage/static-generator
      dockerfile: Dockerfile
      args:
        STATIC_GENETATOR_PORT: ${STATIC_GENERATOR_PORT}
    ports:
      - ${STATIC_GENERATOR_PORT}:${STATIC_GENERATOR_PORT}
    volumes:
      - album-uploads:/srv/album-uploads
      - album-static-gen:/srv/album-static-gen
    restart: on-failure

  exif-core:
    container_name: ${EXIF_CORE_SERVICE}
    build:
      context: ../../src/exif/exif-core
      dockerfile: Dockerfile
      args:
        EXIF_CORE_PORT: ${EXIF_CORE_PORT}
    restart: on-failure

  exif-api:
    container_name: ${EXIF_API_SERVICE}
    build:
      context: ../../src/exif/exif-api
      dockerfile: Dockerfile
      args:
        EXIF_API_PORT: ${EXIF_API_PORT}
    restart: on-failure

  servicex:
    container_name: ${SERVICE_X_SERVICE}
    build:
      context: ../../src/serviceX 
      dockerfile: Dockerfile
    restart: on-failure

volumes:
  album-uploads:
  album-static-gen: