version: '3.5'

services:
  frontend:
    container_name: ${FRONTEND_SERVICE}
    build:
      context: ../../src/frontend 
      dockerfile: Dockerfile
    environment:
     - FRONTEND_PORT=${FRONTEND_PORT}
    ports:
     - ${FRONTEND_PORT}:${FRONTEND_PORT}
    restart: on-failure

  photo-upload-server:
    container_name: photo-upload-server
    build:
      context: ../../src/storage/photo-upload-server
      dockerfile: Dockerfile
    volumes:
      - album-uploads:/usr/src/app/album-uploads
    ports:
      - 8000:8000
    restart: on-failure

volumes:
  album-uploads: